name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.ryangoosling }}
          password: ${{ secrets.900d757c-f4c3-4c96-bcd0-0e0fc2888c31 }}
      -name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.ryangoosling }}/simplewhale:latest
          cache-from: type=registry,ref=${{ secrets.ryangoosling }}/simplewhale:buildcache
          cache-to: type=registry,ref=${{ secrets.ryangoosling }}/simplewhale:buildcache,mode=max
